apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::907938028120:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1JJQ16E49M5O0
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2021-10-13T23:17:12Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1096"
  uid: 68a5e071-0c13-4de8-833a-3da634cfd14a
