apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::907938028120:role/UdacityFlaskDeployCBKubectlRole
      username: build
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::907938028120:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-CEJUBERORAFU
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2021-10-14T12:18:50Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1032"
  uid: 766356f9-da51-4057-b488-a837377bed1f
